{
 "title": "Blackbox Exporter Overview",
 "description": "My version for the 5345 dashboard for many nodes.",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "targets",
    "query": "label_values(probe_success, target)"
   },
   {
    "name": "probes",
    "query": "label_values(probe_success, probe_region)"
   }
  ]
 },
 "panels": [
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "targets" },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(probe_success{target=~\"$targets\",probe_region=~\"$probes\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(probe_http_ssl{target=~\"$targets\",probe_region=~\"$probes\"})"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\",probe_region=~\"$probes\"}",
     "legendFormat": "{{target}} -- {{probe_region}}"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{target=~\"$targets\",probe_region=~\"$probes\"}-time())"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(probe_http_status_code{target=~\"$targets\",probe_region=~\"$probes\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\",probe_region=~\"$probes\"})"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\",probe_region=~\"$probes\"})"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{target=~\"$targets\",probe_region=~\"$probes\"}",
     "legendFormat": "{{target}} - {{probe_region}}"
    }
   ]
  }
 ]
}