{
 "title": "HAproxy Image Server Performance Testing",
 "description": "HAproxy / Image Server Performance Testing",
 "tags": [
  "haproxy",
  "backend"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "alias",
    "label": "Load Balancer",
    "query": "label_values(haproxy_up{job=\"haproxy-exporter\"}, pod)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_backend_http_responses_total{job=\"haproxy-exporter\"}, code)"
   },
   {
    "name": "backend",
    "label": "Service",
    "query": "label_values(thumbor_response_bytes_total, service)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{label_app_kubernetes_io_name=\"image-service\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests - ( Frontend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (irate(haproxy_frontend_http_requests_total{pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{frontend }}"
    }
   ]
  },
  {
   "title": "HTTP Responses - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (backend, code) (irate(haproxy_backend_http_responses_total{backend=~\".*$backend-[0-9].*\", code=~\"$code\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }}/{{ code }}"
    }
   ]
  },
  {
   "title": "Requests Status Code - ( Thumbor )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thumbor_response_status_total{job=\"$deployment\"}[$interval])) by (statuscode)",
     "legendFormat": "{{ statuscode }}"
    }
   ]
  },
  {
   "title": "HAProxy Ingress - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits_cpu_cores{container=\"haproxy\",pod=~\"$alias\"})",
     "legendFormat": "Haproxy CPU Limits"
    },
    {
     "expr": "sum by (container_name,pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name=\"haproxy\",pod_name=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ pod_name }}/{{ container_name }}"
    }
   ]
  },
  {
   "title": "HTTP Responses - ( Backend ) - NOT 2xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (backend, code) (irate(haproxy_backend_http_responses_total{backend=~\".*$backend-[0-9].*\", code!~\"2..\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }}/{{ code }}"
    }
   ]
  },
  {
   "title": "Requests Status Code - ( Thumbor ) - NOT 2xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thumbor_response_status_total{job=\"$deployment\", statuscode!~\"2..\"}[$interval])) by (statuscode)",
     "legendFormat": "{{ statuscode }}"
    }
   ]
  },
  {
   "title": "Percentiles / Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "99-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "95-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "90-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "75-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "50-p  {{backend}}"
    }
   ]
  },
  {
   "title": "Google Bucket Read / Write Response Times ( Thumbor )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(thumbor_gcs_fetch_sum{job=\"$deployment\"}[$interval]) / rate(thumbor_gcs_fetch_count{job=\"$deployment\"}[$interval]) ",
     "legendFormat": "read {{ instance }}"
    },
    {
     "expr": "rate(thumbor_gcs_put_sum{job=\"$deployment\"}[$interval]) / rate(thumbor_gcs_put_count{job=\"$deployment\"}[$interval]) ",
     "legendFormat": "write {{instance}}"
    }
   ]
  },
  {
   "title": "HAProxy Ingress - CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total{container_name=~\".+\",pod_name=~\"haproxy-.*\"}[5m])) / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total{container_name=~\".+\"}[5m]))",
     "legendFormat": "{{ pod_name }} / {{ container_name }}"
    }
   ]
  },
  {
   "title": "App - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits_cpu_cores{container=~\"main\", pod=~\"$backend-.*\"}) by (container)",
     "legendFormat": " {{ container }} - CPU Limitis"
    },
    {
     "expr": "sum by (container_name,pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name=~\"main\", pod_name=~\"$deployment\"}[$interval]))",
     "legendFormat": "{{ pod_name }}/{{ container_name }}"
    }
   ]
  },
  {
   "title": "Queue Size - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (haproxy_backend_max_queue{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - MAX"
    },
    {
     "expr": "sum by (backend) (haproxy_backend_current_queue{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - Current"
    }
   ]
  },
  {
   "title": "Connections - ( backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (irate(haproxy_backend_connection_errors_total{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }} - Error "
    },
    {
     "expr": "sum by (backend) (haproxy_backend_current_session_rate{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - New"
    },
    {
     "expr": "sum by (backend) (haproxy_backend_current_sessions{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - Active"
    }
   ]
  },
  {
   "title": "APP - CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total{container_name=~\"main\", pod_name=~\"$backend-.*\"}[5m])) / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total{container_name=~\".+\"}[5m]))",
     "legendFormat": "{{ pod_name }} / {{ container_name }}"
    }
   ]
  },
  {
   "title": "Bytes - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "(-) IN / (+) OUT" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (irate(haproxy_backend_bytes_in_total{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }}-IN"
    },
    {
     "expr": "sum by (backend) (irate(haproxy_backend_bytes_out_total{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }}-OUT"
    }
   ]
  },
  {
   "title": "Errors - ( Frontend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (irate(haproxy_frontend_request_errors_total{pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ frontend }} - Errors"
    },
    {
     "expr": "sum by (frontend) (irate(haproxy_frontend_requests_denied_total{pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ frontend }} - Denied"
    }
   ]
  },
  {
   "title": "(ES Haproxy) Error TERM State - per $interval",
   "type": "graph",
   "description": "https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.5",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "term_state.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ta_active_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "backend:\"$backend\" AND NOT term_state.keyword:\"----\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Errors - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_response_errors_total{backend=~\".*$backend-[0-9].*\", pod=~\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}