{
 "title": "Thumbor Image Service",
 "description": "Simple thumbor metrics using prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "backend",
    "label": "Service",
    "query": "label_values(kube_service_labels{label_app_kubernetes_io_name=\"image-service\"}, service)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{label_app_kubernetes_io_name=\"image-service\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances Running",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100* min(kube_deployment_status_replicas_available{deployment=\"$deployment\"}) without (instance, pod) / max(kube_deployment_spec_replicas{deployment=\"$deployment\"}) without (instance, pod) ",
     "legendFormat": "Instances up"
    }
   ]
  },
  {
   "title": "Thumbor Response Codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "per-second average rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thumbor_response_status_total{service=\"$backend\"}[$interval])) by (statuscode)",
     "legendFormat": "{{statuscode}} "
    }
   ]
  },
  { "title": "Response Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Percentiles / Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "99-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "95-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "90-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "75-p {{backend}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\".*$backend-[0-9].*\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "50-p {{backend}}"
    }
   ]
  },
  {
   "title": "Google Bucket Read / Write Response Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(thumbor_gcs_fetch_sum{job=\"$deployment\"}[$interval]) / rate(thumbor_gcs_fetch_count{job=\"$deployment\"}[$interval]) ",
     "legendFormat": "read: {{ pod }}"
    },
    {
     "expr": "rate(thumbor_gcs_put_sum{job=\"$deployment\"}[$interval]) / rate(thumbor_gcs_put_count{job=\"$deployment\"}[$interval]) ",
     "legendFormat": "write: {{ pod }}"
    }
   ]
  },
  {
   "title": "Thumbor Response Time (Average)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(thumbor_response_time_sum{job=\"$deployment\", statuscode_extension=\"response.time\"}[$interval]) / rate(thumbor_response_time_count{job=\"$deployment\", statuscode_extension=\"response.time\"}[$interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "[HAProxy] Thumbor Avg Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(thumbor_response_bytes_total{service=\"$backend\"}[$interval]))",
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "backend: \".*$backend-8000.*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[HAProxy] Thumbor Number of Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(thumbor_response_bytes_total{service=\"$backend\"}[$interval]))",
     "metrics": [
      {
       "field": "bytes_read",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "backend: \".*$backend-8000.*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[HAProxy] Thumbor Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(thumbor_response_bytes_total{service=\"$backend\"}[$interval]))",
     "metrics": [
      {
       "field": "ta_active_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "backend: \".*$backend-8000.*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[HAProxy-ES] Thumbor Response Time (Percentiles)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ta_active_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "20",
         "50",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "backend: \".*$backend-8000.*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Mem / CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Per Instance Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=\"main\", pod_name=~\"$deployment-.*\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Per Instance CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"main\", pod_name=~\"$deployment.*\"}[$interval])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Cache Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Storage Miss Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thumbor_storage_miss_total{job=\"$deployment\"}[$interval]))"
    }
   ]
  }
 ]
}