{
 "title": "Mintel /  Cost Analysis by Cluster",
 "description": "Provides an analysis of costs by cluster",
 "tags": [
  "mintel",
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "costcpu", "label": "CPU", "query": "17.76" },
   { "name": "costpcpu", "label": "PE CPU", "query": "5.34" },
   { "name": "costram", "label": "RAM", "query": "2.38" },
   { "name": "costpram", "label": "PE RAM", "query": "0.71" },
   { "name": "costStorageStandard", "label": "Storage", "query": "0.040" },
   { "name": "costStorageSSD", "label": "SSD", "query": "0.170" },
   { "name": "costDiscount", "label": "Disc.", "query": "30" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "This dashboard shows indicative monthly costing for the cluster, based on current requests for CPU, RAM and Storage.\nCurrent Region Prices are for BELGIUM .\n  Utilisation figures represent utilsation of current, active deployments vs\ntheir request limits, and does not include data from instances no longer running.\n"
  },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "description": "This gauge shows the current CPU use vs CPU available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",service=\"kubelet\"}[1m])) / sum (machine_cpu_cores{service=\"kubelet\"}) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "This panel shows current CPU reservation requests by applications, vs CPU available",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores) / sum (kube_node_status_allocatable_cpu_cores)) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(((sum(kube_node_status_capacity_cpu_cores) by (node)\n  * on (node) group_left (label_cloud_google_com_gke_preemptible) kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"})\n  * $costpcpu) or ((sum(kube_node_status_capacity_cpu_cores) by (node)\n  * on (node) group_left (label_cloud_google_com_gke_preemptible) kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"})\n  * ($costcpu - ($costcpu / 100 * $costDiscount))))\n"
    }
   ]
  },
  {
   "title": "Storage Cost (Cluster and PVC)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"})\n  by (persistentvolumeclaim, namespace, storageclass) + on (persistentvolumeclaim, namespace)\n  group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)\n  by (persistentvolumeclaim, namespace)) / 1024 / 1024 / 1024 * $costStorageSSD\n  + (sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"})\n  by (persistentvolumeclaim, namespace, storageclass) + on (persistentvolumeclaim, namespace)\n  group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)\n  by (persistentvolumeclaim, namespace)) / 1024 / 1024 / 1024 or on() vector(0) )* $costStorageStandard\n  + sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id!=\"/\"}) / 1024 / 1024 / 1024 * $costStorageSSD\n"
    }
   ]
  },
  {
   "title": "RAM Utilisation",
   "type": "singlestat",
   "description": "This gauge shows current RAM use by RAM available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",service=\"kubelet\"}) / sum (machine_memory_bytes{service=\"kubelet\"}) * 100\n"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "singlestat",
   "description": "This panel shows current RAM reservation requests by applications, vs RAM available",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(kube_pod_container_resource_requests_memory_bytes)\n    / sum(kube_node_status_allocatable_memory_bytes)) * 100\n"
    }
   ]
  },
  {
   "title": "RAM Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(((\n       sum(kube_node_status_capacity_memory_bytes) by (node)\n        * on (node) group_left (label_cloud_google_com_gke_preemptible)\n       kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}\n     ) /1024/1024/1024 * $costpram)\n   or\n   ((\n       sum(kube_node_status_capacity_memory_bytes) by (node)\n        * on (node) group_left (label_cloud_google_com_gke_preemptible)\n       kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n     ) /1024/1024/1024 * ($costram - ($costram / 100 * $costDiscount))))\n"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "# CPU\nsum(((sum(kube_node_status_capacity_cpu_cores) by (node) * on (node) group_left (label_cloud_google_com_gke_preemptible)\nkube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}) * $costpcpu)\nor ((sum(kube_node_status_capacity_cpu_cores) by (node) * on (node) group_left (label_cloud_google_com_gke_preemptible)\nkube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}) * ($costcpu - ($costcpu / 100 * $costDiscount)))) +\n# Storage\nsum (\nsum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n+ on (persistentvolumeclaim, namespace) group_right(storageclass)\nsum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) / 1024 / 1024 /1024 * $costStorageSSD +\n(sum (\nsum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n+ on (persistentvolumeclaim, namespace) group_right(storageclass)\nsum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) or on() vector(0)) / 1024 / 1024 /1024 * $costStorageStandard +\nsum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id!=\"/\"}) / 1024 / 1024 / 1024 * $costStorageSSD +\n# RAM\nsum(((\n    sum(kube_node_status_capacity_memory_bytes) by (node)\n     * on (node) group_left (label_cloud_google_com_gke_preemptible)\n    kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}) /1024/1024/1024 * $costpram\n)\nor\n((\n    sum(kube_node_status_capacity_memory_bytes) by (node)\n     * on (node) group_left (label_cloud_google_com_gke_preemptible)\n    kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n  ) /1024/1024/1024 * ($costram - ($costram / 100 * $costDiscount))\n))\n"
    }
   ]
  },
  {
   "title": "Cluster Node Utilisation by CPU and RAM requests",
   "type": "table",
   "description": "This table shows the comparison of CPU and RAM requests by applications, vs the capacity of the node",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes) by (node) / sum(kube_node_status_allocatable_memory_bytes) by (node)) * 100\n",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores) by (node) / sum(kube_node_status_allocatable_cpu_cores) by (node)) * 100\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Namespace cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (namespace) (namespace_name:kube_pod_container_resource_requests_cpu_cores:sum) * ($costcpu - ($costcpu / 100 * $costDiscount)) )\n  +(sum(container_spec_cpu_shares{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by (namespace)\n  or count(count(container_spec_cpu_shares{namespace!=\"\"}) by (namespace)) by (namespace) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "(sum by (namespace) (namespace_name:kube_pod_container_resource_requests_memory_bytes:sum)/1024/1024/1024*($costram- ($costram\n  / 100 * $costDiscount)))+(sum(container_spec_memory_limit_bytes{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram)\n  by (namespace) or count(count(container_spec_memory_limit_bytes{namespace!=\"\"}) by (namespace)) by (namespace) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on (persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)\n  by (persistentvolumeclaim, namespace)) by (namespace) / 1024 / 1024 / 1024 * $costStorageSSD\n  or sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"})\n  by (persistentvolumeclaim, namespace, storageclass) + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace))\n  by (namespace) / 1024 / 1024 / 1024 * $costStorageStandard or count(count(container_spec_cpu_shares{namespace!=\"\"}) by (namespace)) by (namespace) -1\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "# Add the CPU\n  ((sum by (namespace) (namespace_name:kube_pod_container_resource_requests_cpu_cores:sum) * ($costcpu - ($costcpu / 100 * $costDiscount)))\n  + (sum(container_spec_cpu_shares{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu)\n  by (namespace) or count(count(container_spec_cpu_shares{namespace!=\"\"}) by (namespace)) by (namespace) -1)) +\n  # Add the RAM\n  ((sum by (namespace) (namespace_name:kube_pod_container_resource_requests_memory_bytes:sum)/1024/1024/1024*($costram- ($costram / 100 * $costDiscount)))\n  + (sum(container_spec_memory_limit_bytes{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram)\n  by (namespace) or count(count(container_spec_memory_limit_bytes{namespace!=\"\"}) by (namespace)) by (namespace) -1)) +\n  # Add the storage\n  (sum (sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)\n  by (persistentvolumeclaim, namespace)) by (namespace) / 1024 / 1024 / 1024 * $costStorageSSD\n  or sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on (persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)\n  by (persistentvolumeclaim, namespace)) by (namespace) / 1024 / 1024 / 1024 * $costStorageStandard\n  or count(count(container_spec_cpu_shares{namespace!=\"\"}) by (namespace)) by (namespace) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "(sum by (namespace) (rate(container_cpu_usage_seconds_total{container_name!=\"\",image!=\"\",service=\"kubelet\"}[1m]))\n  /  ignoring(namespace) group_left() (sum (kube_node_status_allocatable_cpu_cores)) ) * 100\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(count(count(container_memory_working_set_bytes{namespace!=\"\"}) by (pod_name, namespace)) by (pod_name, namespace) *\n  on (pod_name, namespace) sum(avg_over_time(container_memory_working_set_bytes{namespace!=\"\"}[1m]))\n  by (pod_name, namespace)) by (namespace) / sum(container_spec_memory_limit_bytes{namespace!=\"\"}) by (namespace) * 100\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum (sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on(persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)\n  by (persistentvolumeclaim, namespace)) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 / 1024 * $costStorageSSD\n  or sum (sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass) +\n  on(persistentvolumeclaim, namespace) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)\n  by (persistentvolumeclaim, namespace)) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 / 1024 * $costStorageStandard\n",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}