{
 "title": "Mintel /  Cost Analysis by Pod",
 "description": "Provides an analysis of costs by pod",
 "tags": [
  "mintel",
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "costcpu", "label": "CPU", "query": "$._config.cost_cpu" },
   { "name": "costpcpu", "label": "PE CPU", "query": "$._config.cost_pcpu" },
   { "name": "costram", "label": "RAM", "query": "$._config.cost_ram" },
   { "name": "costpram", "label": "PE RAM", "query": "$._config.cost_pram" },
   {
    "name": "costStorageStandard",
    "label": "Storage",
    "query": "$._config.cost_storage_standard"
   },
   { "name": "costStorageSSD", "label": "SSD", "query": "$._config.cost_storage_ssd" },
   { "name": "costDiscount", "label": "Disc.", "query": "$._config.cost_discount" },
   {
    "name": "namespace",
    "label": "NS",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod_name))"
   }
  ]
 },
 "panels": [
  {
   "title": "Container cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}/1000*\n($costcpu - ($costcpu / 100 * $costDiscount))) by(container_name)  or  count(\ncount(container_spec_cpu_shares{namespace=\"$namespace\",container_name!=\"POD\",pod_name=\"$pod\"})\nby(container_name)  ) by(container_name) -1)+(  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",\ncontainer_name!=\"POD\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by(container_name)  or\ncount(    count(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}) by(container_name)  ) by(container_name) -1)\n",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "(  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}\n/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(container_name)\nor  count(    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}) by(container_name)  )\nby(container_name) -1)+(  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",cloud_google_com_gke_preemptible=\"true\"}\n/1024/1024/1024*$costpram) by(container_name)  or  count(    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"})\nby(container_name)  ) by(container_name) -1)\n",
     "legendFormat": "{{ namespace }}"
    },
    { "expr": "vector(0)\n", "legendFormat": "{{ namespace }}" },
    {
     "expr": "(  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}/1000\n*($costcpu - ($costcpu / 100 * $costDiscount))) by(container_name)  or  count(    count(container_spec_cpu_shares{namespace=\"$namespace\",container_name!=\"POD\",pod_name=\"$pod\"})\nby(container_name)  ) by(container_name) -1)+(  sum(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",cloud_google_com_gke_preemptible=\"true\"}\n/1000*$costpcpu) by(container_name)  or count(    count(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}) by(container_name)  )\nby(container_name) -1)+(  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",cloud_google_com_gke_preemptible!=\"true\"}\n/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))) by(container_name)\nor  count(    count(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"})\nby(container_name)  ) by(container_name) -1)+(  sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\",\ncloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram) by(container_name)  or  count(\ncount(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}) by(container_name)  ) by(container_name) -1)\n"
    },
    {
     "expr": "sum(   count(count(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}) by (container_name))\nby (container_name)     * on (container_name)    sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}[1m]))\nby (container_name)) by (container_name) * 1000/sum(container_spec_cpu_shares{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}) by (container_name) * 100\n",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum(   count(count(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"})\nby (container_name)) by (container_name)     * on (container_name)\nsum(avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}[1m]))\nby (container_name)) by (container_name)/sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod_name=\"$pod\",container_name!=\"POD\"}) by (container_name) * 100\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Core Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you CPU use of your application vs its requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}[1m])) by (container_name)\n",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "sum(container_spec_cpu_shares{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name) / 1000\n",
     "legendFormat": "{{ container_name }} (requested)"
    }
   ]
  },
  {
   "title": "RAM Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you RAM use of your application vs its requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time (container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}[1m])) by (container_name)\n",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)\n",
     "legendFormat": "{{ container_name }} (requested)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this pod, as a sum of its containers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[1m])) by (pod_name)\n",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[1m])) by (pod_name)\n",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk read writes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[1m])) by (pod_name)\n",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}[1m])) by (pod_name)\n",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}