{
 "title": "HAproxy App Performance",
 "description": "HAproxy / Image Server Performance Testing",
 "tags": [
  "haproxy",
  "backend"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "alias",
    "label": "Load Balancer",
    "query": "label_values(haproxy_up{job=\"haproxy-exporter\"}, pod)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_backend_http_responses_total{job=\"haproxy-exporter\"}, code)"
   },
   {
    "name": "app",
    "label": "app",
    "query": ".*openresty-.*, .*image-service-production-.*"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests - ( Frontend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (irate(haproxy_frontend_http_requests_total{pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{frontend }}"
    }
   ]
  },
  {
   "title": "HTTP Responses - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (backend, code) (irate(haproxy_backend_http_responses_total{backend=~\"$app\", code=~\"$code\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }}/{{ code }}"
    }
   ]
  },
  {
   "title": "(ES Haproxy) Status Code for App / Backend - per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ta_active_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "backend:\"$app\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HAProxy Ingress - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits_cpu_cores{container=\"haproxy\",pod=~\"$alias\"})",
     "legendFormat": "Haproxy CPU Limits"
    },
    {
     "expr": "sum by (container,pod)(rate(container_cpu_usage_seconds_total{image!=\"\",container=\"haproxy\",pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "App - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits_cpu_cores{container=~\"$app\", pod=~\"$app\"}) by (container)",
     "legendFormat": " {{ container }} - CPU Limitis"
    },
    {
     "expr": "sum by (container,pod)(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"$app\", pod=~\"$app\"}[$interval]))",
     "legendFormat": "{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Queue Size - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (haproxy_backend_max_queue{backend=~\"$app\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - MAX"
    },
    {
     "expr": "sum by (backend) (haproxy_backend_current_queue{backend=~\"$app\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - Current"
    }
   ]
  },
  {
   "title": "HAProxy Ingress - CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{container=~\".+\",pod=~\"haproxy-.*\"}[5m])) / sum by(container, pod, namespace) (increase(container_cpu_cfs_periods_total{container=~\".+\"}[5m]))",
     "legendFormat": "{{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "(ES Haproxy) Error TERM State - per $interval",
   "type": "graph",
   "description": "https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.5",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "term_state.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ta_active_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "backend:\"$app\" AND NOT term_state.keyword:\"----\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Connections - ( backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (irate(haproxy_backend_connection_errors_total{backend=~\"$app\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }} - Error "
    },
    {
     "expr": "sum by (backend) (haproxy_backend_current_session_rate{backend=~\"$app\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - New"
    },
    {
     "expr": "sum by (backend) (haproxy_backend_current_sessions{backend=~\"$app\", pod=~\"$alias\"})",
     "legendFormat": "{{ backend }} - Active"
    }
   ]
  },
  {
   "title": "Percentiles / Request Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\"$app\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "99-p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\"$app\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "95-p"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\"$app\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "90-p"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\"$app\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "75-p"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_backend_request_duration_seconds_bucket{backend=~\"$app\"}[$interval])) by (backend,job,le) )",
     "legendFormat": "50-p "
    }
   ]
  },
  {
   "title": "Bytes - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "(-) IN / (+) OUT" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (irate(haproxy_backend_bytes_in_total{backend=~\"$app\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }}-IN"
    },
    {
     "expr": "sum by (backend) (irate(haproxy_backend_bytes_out_total{backend=~\"$app\", pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ backend }}-OUT"
    }
   ]
  },
  {
   "title": "Response Errors - ( Backend )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_response_errors_total{backend=~\"$app\", pod=~\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Conntrack Entries % Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-node:conntrack_entries_free:percentage{job=\"monitoring/node-exporter\"}",
     "legendFormat": "{{  instance }}"
    }
   ]
  },
  {
   "title": "Errors - ( Frontend )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (irate(haproxy_frontend_request_errors_total{pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ frontend }} - Errors"
    },
    {
     "expr": "sum by (frontend) (irate(haproxy_frontend_requests_denied_total{pod=~\"$alias\"}[$interval]))",
     "legendFormat": "{{ frontend }} - Denied"
    }
   ]
  }
 ]
}