{
 "title": "Fluentd dashboard",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(fluentd_output_status_buffer_queue_length,service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fluentd Up",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Fluentd incoming records rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{service=\"$service\"}[1m])) by (host)\n",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Fluentd output error/retry rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type,plugin_id)  (rate(fluentd_output_status_retry_count{service=~\"$service\",type!=\"null\"}[1m]))",
     "legendFormat": "Retry: {{ type }} - {{ plugin_id }}"
    },
    {
     "expr": "sum by (type,plugin_id)  (rate(fluentd_output_status_num_errors{service=~\"$service\",type!=\"null\"}[1m]))",
     "legendFormat": "Error: {{ type }} - {{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Fluentd output emit/s by Plugin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type,plugin_id) (rate(fluentd_output_status_emit_count{service=~\"$service\",type!=\"null\"}[1m]))",
     "legendFormat": "{{type}} - {{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Fluentd output emit/s by Plugin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_retry_wait{service=~\"$service\"}[1m])",
     "legendFormat": "{{type}} - {{ plugin_id }}"
    }
   ]
  },
  {
   "title": "maximum output buffer length in last 1min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_buffer_queue_length{service=\"$service\"}[1m])",
     "legendFormat": "{{host}} - {{plugin_id}}"
    }
   ]
  },
  {
   "title": "maximum output buffer size in last 1min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_buffer_total_bytes{service=\"$service\"}[1m])",
     "legendFormat": "{{host}} - {{plugin_id}}"
    }
   ]
  }
 ]
}