{
 "title": "Kubernetes Cluster Health",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!~\"DeadMansSwitch|Watchdog\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!~\"DeadMansSwitch|Watchdog\"})"
    }
   ]
  },
  {
   "title": "TargetDown is Firing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 + (absent(sum(ALERTS{alertname=\"TargetDown\",alertstate=\"firing\"})) or vector(0))"
    }
   ]
  },
  {
   "title": "Node Conditions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\", status=\"true\"} )"
    }
   ]
  },
  {
   "title": "Alert Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ALERTS{alertname!~\"DeadMansSwitch|Watchdog\"}"
    }
   ]
  },
  { "title": "Pods Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[1h]) > 5)"
    }
   ]
  },
  {
   "title": "StatefulSet replica Mismatch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"KubeStatefulSetReplicasMismatch\"})"
    }
   ]
  },
  {
   "title": "Deployment replicas not updated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DeploymentReplicasNotUpdated\"})"
    }
   ]
  },
  {
   "title": "DaemonSet Rollout Stuck",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DaemonSetRolloutStuck\"})"
    }
   ]
  },
  {
   "title": "DaemonSet Not Scheduled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"K8SDaemonSetsNotScheduled\"})"
    }
   ]
  },
  {
   "title": "OOM Killed Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count by (pod)(kube_pod_container_status_terminated_reason{reason=\"OOMKilled\"}))"
    }
   ]
  },
  { "title": "Nodes Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Nodes With low Cpu Cores for new pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname=\"NodeCpuAvailableForPodsLow\"})"
    }
   ]
  },
  {
   "title": "Nodes With low Memory for new pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname=\"NodeMemoryAvailableForPodsLow\"})"
    }
   ]
  }
 ]
}