{
 "title": "Kubernetes Capacity Planning",
 "tags": [
  "kubernetes",
  "capacity"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores Requests - Worker Nodes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^gke.*\"}) by (service)) / min(sum(kube_node_status_allocatable_cpu_cores{node=~\"^gke.*\"}) by (service))"
    }
   ]
  },
  {
   "title": "Idle CPU - Worker Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "avg(\n   rate(node_cpu{mode=\"idle\"}[2m]) \n   * on(instance) group_left(nodename) \n   node_uname_info{nodename=~\"^gke.*\"} * 100\n) by (mode)",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores - Worker Nodes",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores{node=~\"^gke.*\"}) by (service))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^gke.*\"}) by (service))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "Cpu Allocated - Worker Nodes",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node=~\"^gke.*\"}) by (node) / sum (kube_node_status_allocatable_cpu_cores{node=~\"^gke.*\"}) by (node)"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests - Worker Nodes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes{node=~\"^gke.*\"}) by (service)) / min(sum(kube_node_status_allocatable_memory_bytes{node=~\"^gke.*\"}) by (service))"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "description": "Physical memory available across all nodes as reported by the OS (through node exporter).",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Kubernetes Memory",
   "type": "graph",
   "description": "Based on figures from kube-state-metrics. This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nThe Allocatable memory is the memory left after system process (journald, sshd, kubelet, kube-proxy, etc…) usage has been deducted.",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Allocated - Worker Nodes",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 7 },
   "format": "none",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node=~\"^gke.*\"}) by (node) / sum (kube_node_status_allocatable_memory_bytes{node=~\"^gke.*\"}) by (node)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(node:node_filesystem_avail: - node:node_filesystem_usage:) / sum(node:node_filesystem_avail:)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"sd(a9|[b-z])\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"sd(a9|[b-z])\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{device=~\"sd(a9|[b-z])\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Usage - Worker Nodes",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 14 },
   "format": "none",
   "targets": [
    {
     "expr": "100 * avg(node:node_filesystem_usage: * on(instance) group_left(nodename) node_uname_info{nodename=~\"^gke.*\"}) by (nodename)"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}