{
 "title": "Prometheus Redis",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   {
    "name": "Job",
    "label": "Redis Cluster",
    "query": "label_values(redis_up{namespace=\"$Namespace\"}, job)"
   },
   {
    "name": "Instance",
    "query": "label_values(redis_up{namespace=\"$Namespace\", job=\"$Job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{job=\"$Job\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(redis_memory_used_bytes{instance=~\"$Instance\"})  / sum(redis_memory_max_bytes{instance=~\"$Instance\"}))"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=~\"$Job\"}[5m])",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{job=\"$Job\"}[5m])",
     "legendFormat": "{{ alias }} hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{job=\"$Job\"}[5m])",
     "legendFormat": "{{ alias}} misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"$Job\"} ",
     "legendFormat": "{{ alias }} used"
    },
    {
     "expr": "redis_memory_max_bytes{job=\"$Job\"} ",
     "legendFormat": "{{ alias }} max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=\"$Job\"}[5m])",
     "legendFormat": "{{ alias }} Outgoing"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=\"$Job\"}[5m])",
     "legendFormat": "{{ alias }} Incoming"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$Job\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$Job\"}) - sum (redis_db_keys_expiring{job=~\"$Job\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{job=~\"$Job\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Command time in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_commands_duration_seconds_total{job=~\"$Job\"}[5m])",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{job=\"$Job\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Slave Replication Offset",
   "type": "graph",
   "description": "Shows the Redis replication offsets for the master and all slaves.   Ideally, all these numbers should be close with the current master slightly ahead.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_master_repl_offset{job=\"$Job\"}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Slave replication lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_slave_lag_seconds{job=\"$Job\"} * on(slave_ip) group_left(pod) label_replace(redis_slave_info,\"slave_ip\",\"$1\",\"instance\",\"(.*):[0-9]+\")",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=~\"$Job\"}[5m])) by (job)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=~\"$Job\"}[5m])) by (job)",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}