{
 "title": "Analysis by Cluster",
 "description": "A dashboard to help with cost and utilisation",
 "tags": [
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "costcpu", "label": "CPU", "query": "18.7" },
   { "name": "costram", "label": "RAM", "query": "3.57" },
   { "name": "costStorageStandard", "label": "Storage", "query": "0.040" },
   { "name": "costStorageSSD", "label": "SSD", "query": "0.170" },
   { "name": "costDiscount", "label": "Disc.", "query": "30" },
   { "name": "costpcpu", "label": "CPU Preemptible", "query": "5.6" },
   { "name": "costpram", "label": "RAM Preemptible", "query": "0.75" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "This dashboard shows indicative monthly costing for the cluster, based on **current** requests for CPU, RAM and Storage. Current Region Prices are for **BELGIUM** .  \nUtilisation figures represent utilsation of current, active deployments vs their request limits, and **does not** include data from instances no longer running."
  },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "description": "This gauge shows the current CPU use vs CPU available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",service=\"kubelet\"}[1m])) / sum (machine_cpu_cores{service=\"kubelet\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "This panel shows current CPU reservation requests by applications, vs CPU available",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(kube_pod_container_resource_requests_cpu_cores)\n  / \n  sum (kube_node_status_allocatable_cpu_cores)\n) * 100"
    }
   ]
  },
  {
   "title": "CPU Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 2 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n      (\n        (\n          sum(kube_node_status_capacity_cpu_cores) by (node)\n          * on (node) group_left (label_cloud_google_com_gke_preemptible)\n          kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}\n        ) * $costpcpu\n      )\n      or\n      (\n        (\n          sum(kube_node_status_capacity_cpu_cores) by (node)\n          * on (node) group_left (label_cloud_google_com_gke_preemptible)\n          kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n          ) * ($costcpu - ($costcpu / 100 * $costDiscount)\n        )\n      )\n)",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Storage Cost (Cluster and PVC)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) / 1024 / 1024 /1024 * $costStorageSSD\n\n+\n\n(sum (\n  sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) / 1024 / 1024 /1024 or on() vector(0) )* $costStorageStandard\n\n+ \n\nsum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"}) / 1024 / 1024 / 1024 * $costStorageSSD",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Cluster Node Utilisation by CPU and RAM requests",
   "type": "table",
   "description": "This table shows the comparison of CPU and RAM requests by applications, vs the capacity of the node",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_memory_bytes) by (node) \n  /\n  sum(kube_node_status_allocatable_memory_bytes) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_cpu_cores) by (node) \n  /\n  sum(kube_node_status_allocatable_cpu_cores) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "RAM Utilisation",
   "type": "singlestat",
   "description": "This gauge shows current RAM use by RAM available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",service=\"kubelet\"}) / sum (machine_memory_bytes{service=\"kubelet\"}) * 100"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "singlestat",
   "description": "This panel shows current RAM reservation requests by applications, vs RAM available",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(kube_pod_container_resource_requests_memory_bytes)\n  /\n  sum(kube_node_status_allocatable_memory_bytes)\n) * 100"
    }
   ]
  },
  {
   "title": "RAM Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 6 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  (\n    (\n      sum(kube_node_status_capacity_memory_bytes) by (node)\n       * on (node) group_left (label_cloud_google_com_gke_preemptible)\n      kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}\n    ) /1024/1024/1024 * $costpram\n  )\n  or\n  (\n    (\n      sum(kube_node_status_capacity_memory_bytes) by (node)\n       * on (node) group_left (label_cloud_google_com_gke_preemptible)\n      kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n    ) /1024/1024/1024 * ($costram - ($costram / 100 * $costDiscount))\n)\n) ",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "# CPU\nsum(\n      (\n        (\n          sum(kube_node_status_capacity_cpu_cores) by (node)\n          * on (node) group_left (label_cloud_google_com_gke_preemptible)\n          kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}\n        ) * $costpcpu\n      )\n      or\n      (\n        (\n          sum(kube_node_status_capacity_cpu_cores) by (node)\n          * on (node) group_left (label_cloud_google_com_gke_preemptible)\n          kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n          ) * ($costcpu - ($costcpu / 100 * $costDiscount)\n        )\n      )\n) \n\n+ \n\n# Storage\nsum (\n  sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) / 1024 / 1024 /1024 * $costStorageSSD\n\n+\n\n(sum (\n  sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) or on() vector(0)) / 1024 / 1024 /1024 * $costStorageStandard\n\n+ \n\nsum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"}) / 1024 / 1024 / 1024 * $costStorageSSD\n\n+ \n# RAM\nsum(\n  (\n    (\n      sum(kube_node_status_capacity_memory_bytes) by (node)\n       * on (node) group_left (label_cloud_google_com_gke_preemptible)\n      kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}\n    ) /1024/1024/1024 * $costpram\n  )\n  or\n  (\n    (\n      sum(kube_node_status_capacity_memory_bytes) by (node)\n       * on (node) group_left (label_cloud_google_com_gke_preemptible)\n      kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n    ) /1024/1024/1024 * ($costram - ($costram / 100 * $costDiscount))\n)\n) ",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Namespace cost and utilisation analysis",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(\n  sum by (namespace) (namespace_name:kube_pod_container_resource_requests_cpu_cores:sum) * ($costcpu - ($costcpu / 100 * $costDiscount)) \n)\n\n+\n\n(\n  sum(container_spec_cpu_shares{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by(namespace)\n  or\n  count(\n    count(container_spec_cpu_shares{namespace!=\"\"}) by(namespace)\n  ) by(namespace) -1\n)",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "(\n  sum by (namespace) (namespace_name:kube_pod_container_resource_requests_memory_bytes:sum)/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))\n)\n\n+\n\n(\n  sum(container_spec_memory_limit_bytes{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram) by(namespace)\n  or\n  count(\n    count(container_spec_memory_limit_bytes{namespace!=\"\"}) by(namespace)\n  ) by(namespace) -1\n)",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (\n  sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) by (namespace) / 1024 / 1024 /1024 * $costStorageSSD\nor sum (\n    sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n    + on (persistentvolumeclaim, namespace) group_right(storageclass)\n    sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) by (namespace) / 1024 / 1024 /1024 * $costStorageStandard\nor\n    count(\n      count(container_spec_cpu_shares{namespace!=\"\"}) by(namespace)\n    ) by(namespace) -1",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "# Add the CPU\n(\n(\n  sum by (namespace) (namespace_name:kube_pod_container_resource_requests_cpu_cores:sum) * ($costcpu - ($costcpu / 100 * $costDiscount)) \n)\n  \n  +\n  \n  (\n    sum(container_spec_cpu_shares{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1000*$costpcpu) by(namespace)\n    or\n    count(\n      count(container_spec_cpu_shares{namespace!=\"\"}) by(namespace)\n    ) by(namespace) -1\n  )\n)\n\n+ \n# Add the RAM\n(\n(\n  sum by (namespace) (namespace_name:kube_pod_container_resource_requests_memory_bytes:sum)/1024/1024/1024*($costram- ($costram / 100 * $costDiscount))\n)\n\n  \n  +\n  \n  (\n    sum(container_spec_memory_limit_bytes{namespace!=\"\",cloud_google_com_gke_preemptible=\"true\"}/1024/1024/1024*$costpram) by(namespace)\n    or\n    count(\n      count(container_spec_memory_limit_bytes{namespace!=\"\"}) by(namespace)\n    ) by(namespace) -1\n  )\n)\n\n+\n# Add the storage\n(\n\n  sum (\n    sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n    + on (persistentvolumeclaim, namespace) group_right(storageclass)\n    sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n  ) by (namespace) / 1024 / 1024 /1024 * $costStorageSSD\n  \n  or\n  \n  sum (\n    sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n    + on (persistentvolumeclaim, namespace) group_right(storageclass)\n    sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n  ) by (namespace) / 1024 / 1024 /1024 * $costStorageStandard\n  \n  or\n  \n  count(\n    count(container_spec_cpu_shares{namespace!=\"\"}) by(namespace)\n  ) by(namespace) -1\n\n)"
    },
    {
     "expr": "( sum by (namespace) (rate(container_cpu_usage_seconds_total{container_name!=\"\",image!=\"\",service=\"kubelet\"}[1m]))  /  ignoring(namespace) group_left() (sum (kube_node_status_allocatable_cpu_cores)) ) * 100",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(\n   count(count(container_memory_working_set_bytes{namespace!=\"\"}) by (pod_name, namespace)) by (pod_name, namespace)  \n   * on (pod_name, namespace) \n   sum(avg_over_time(container_memory_working_set_bytes{namespace!=\"\"}[1m])) by (pod_name, namespace)\n) by (namespace)\n/\nsum(container_spec_memory_limit_bytes{namespace!=\"\"}) by (namespace) * 100\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum (\n  sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*|fast\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 /1024 * $costStorageSSD\n\nor\n\nsum (\n  sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n  + on (persistentvolumeclaim, namespace) group_right(storageclass)\n  sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) by (namespace,persistentvolumeclaim,storageclass) / 1024 / 1024 /1024 * $costStorageStandard\n",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}