{
 "title": "Vault Deployments",
 "description": " ",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": "label_values(vault_sys_initialized, vault_cr)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Un-Sealed Vault instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "( count by (vault_cr) (vault_sys_sealed{vault_cr=\"$Instance\"}==0)  / count by (vault_cr) (vault_sys_sealed{vault_cr=\"$Instance\"}) ) * 100"
    }
   ]
  },
  {
   "title": "Modify by Path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"create|delete|renew|update\", vault_cr=\"$Instance\"}[1m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  {
   "title": "Read by Path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"read\", vault_cr=\"$Instance\"}[1m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  {
   "title": "Initialized Vaults in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "( count by (vault_cr) (vault_sys_initialized{vault_cr=\"$Instance\"}==1)  / count by (vault_cr) (vault_sys_initialized{vault_cr=\"$Instance\"}) ) * 100"
    }
   ]
  },
  {
   "title": "Current Leader",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "vault_sys_leader{vault_cr=\"$Instance\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leadership Losses in the last 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (vault_cr) (increase(vault_core_leadership_lost_count{job=\"vault/vault\"}[1h]))"
    }
   ]
  },
  {
   "title": "Duration of requests handled by the Vault core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vault_core_handle_request{vault_cr=\"$Instance\"} > 0",
     "legendFormat": "{{pod}}:{{quantile}}"
    }
   ]
  },
  {
   "title": "Vault Applied Configurations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vault_config_successful{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(vault_config_failed{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "Failures"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pending Tokens",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vault_token_create_count{vault_cr=\"$Instance\"}-vault_token_store_count{vault_cr=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Token Lookup rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_token_lookup_count{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "Lookup"
    }
   ]
  },
  {
   "title": "Token",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vault_token_create_count{vault_cr=\"$Instance\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(vault_token_store_count{vault_cr=\"$Instance\"})",
     "legendFormat": "Store"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Audit Log Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vault_audit_log_request_count{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "sum(irate(vault_audit_log_response_count{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "sum(irate(vault_core_handle_request_count{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Auth Rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"rollback\",vault_cr=\"$Instance\"}[1m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Policy Set",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_set_policy_count{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "set"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count{vault_cr=\"$Instance\"}[1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "Google Cloud Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Cloud Storage List",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(vault_gcs_list_count{vault_cr=\"$Instance\"}[10m]))",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "Cloud Storage GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_gcs_get_count{vault_cr=\"$Instance\"}[10m])",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Cloud Storage Delete",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_gcs_delete_count{vault_cr=\"$Instance\"}[10m])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Cloud Storage PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(vault_gcs_put_sum{vault_cr=\"$Instance\"}[5m])",
     "legendFormat": "PUT"
    }
   ]
  }
 ]
}