{
 "title": "Flux Daemon Metrics",
 "description": "Dashboard for Weave Flux",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(flux_daemon_sync_duration_seconds_sum, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Duration of git-to-cluster synchronisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_daemon_sync_duration_seconds_sum{job=\"$instance\"}[5m])) by (success, namespace)",
     "legendFormat": "{{namespace}} - success: {{success}}"
    }
   ]
  },
  {
   "title": "Duration of remote image metadata requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_client_fetch_duration_seconds_sum{job=\"$instance\"}[5m])) by (kind, namespace)",
     "legendFormat": "{{namespace}} - {{kind}}"
    }
   ]
  },
  {
   "title": "Duration of cache requests, in seconds.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_cache_request_duration_seconds_sum{job=\"$instance\"}[5m])) by (method, namespace)",
     "legendFormat": "{{namespace}} - {{method}}"
    }
   ]
  },
  {
   "title": "Duration of time spent in the job queue before execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flux_daemon_queue_duration_seconds_sum{job=~\"$instance\"}",
     "legendFormat": "Total {{namespace}}"
    }
   ]
  },
  {
   "title": "Duration of job execution, in seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(flux_daemon_job_duration_seconds_bucket{job=\"$instance\"}[$__interval])) by (le, namespace, success))",
     "legendFormat": "{{namespace}} success - {{success}}"
    }
   ]
  },
  {
   "title": "Duration in seconds of the current connection to fluxsvc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_fluxd_connection_duration_seconds{job=\"$instance\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}} - Connection duration"
    }
   ]
  },
  {
   "title": "Count of jobs waiting in the queue to be run",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flux_daemon_queue_length_count", "legendFormat": "{{namespace}} - jobs" }
   ]
  },
  {
   "title": "Duration of image metadata requests (from cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_registry_fetch_duration_seconds_sum{job=\"$instance\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}} - Registry fetch"
    }
   ]
  }
 ]
}